/* client functions auto-generated by pidl */

#include "includes.h"
#include <tevent.h>
#include "lib/util/tevent_ntstatus.h"
#include "bin/default/librpc/gen_ndr/ndr_messaging.h"
#include "bin/default/librpc/gen_ndr/ndr_messaging_c.h"

/* messaging - client functions generated by pidl */

