
/* Python wrapper functions auto-generated by pidl */
#define PY_SSIZE_T_CLEAN 1 /* We use Py_ssize_t for PyArg_ParseTupleAndKeywords */
#include <Python.h>
#include "python/py3compat.h"
#include "includes.h"
#include <pytalloc.h>
#include "librpc/rpc/pyrpc.h"
#include "librpc/rpc/pyrpc_util.h"
#include "bin/default/librpc/gen_ndr/ndr_dsbackup.h"
#include "bin/default/librpc/gen_ndr/ndr_dsbackup_c.h"

/*
 * These functions are here to ensure they can be optimized out by
 * the compiler based on the constant input values
 */

static inline unsigned long long ndr_sizeof2uintmax(size_t var_size)
{
	switch (var_size) {
	case 8:
		return UINT64_MAX;
	case 4:
		return UINT32_MAX;
	case 2:
		return UINT16_MAX;
	case 1:
		return UINT8_MAX;
	}

	return 0;
}

static inline long long ndr_sizeof2intmax(size_t var_size)
{
	switch (var_size) {
	case 8:
		return INT64_MAX;
	case 4:
		return INT32_MAX;
	case 2:
		return INT16_MAX;
	case 1:
		return INT8_MAX;
	}

	return 0;
}

static inline PyObject *ndr_PyLong_FromLongLong(long long v)
{
	if (v > LONG_MAX || v < LONG_MIN) {
		return PyLong_FromLongLong(v);
	} else {
		return PyInt_FromLong(v);
	}
}

static inline PyObject *ndr_PyLong_FromUnsignedLongLong(unsigned long long v)
{
	if (v > LONG_MAX) {
		return PyLong_FromUnsignedLongLong(v);
	} else {
		return PyInt_FromLong(v);
	}
}

static PyTypeObject ad_backup_InterfaceType;

static PyTypeObject ad_restore_InterfaceType;

static PyTypeObject *ClientConnection_Type;
static PyTypeObject *ndr_syntax_id_Type;

const struct PyNdrRpcMethodDef py_ndr_ad_backup_methods[] = {
	{ NULL }
};

static PyObject *interface_ad_backup_new(PyTypeObject *type, PyObject *args, PyObject *kwargs)
{
	return py_dcerpc_interface_init_helper(type, args, kwargs, &ndr_table_ad_backup);
}

#define PY_DOC_AD_BACKUP "Backup support for Active Directory"
static PyTypeObject ad_backup_InterfaceType = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "dsbackup.ad_backup",
	.tp_basicsize = sizeof(dcerpc_InterfaceObject),
	.tp_doc = "ad_backup(binding, lp_ctx=None, credentials=None) -> connection\n"
"\n"
"binding should be a DCE/RPC binding string (for example: ncacn_ip_tcp:127.0.0.1)\n"
"lp_ctx should be a path to a smb.conf file or a param.LoadParm object\n"
"credentials should be a credentials.Credentials object.\n\n"PY_DOC_AD_BACKUP,
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = interface_ad_backup_new,
};

static PyObject *syntax_ad_backup_new(PyTypeObject *type, PyObject *args, PyObject *kwargs)
{
	return py_dcerpc_syntax_init_helper(type, args, kwargs, &ndr_table_ad_backup.syntax_id);
}

#define PY_DOC_AD_BACKUP_SYNTAX "Backup support for Active Directory"
static PyTypeObject ad_backup_SyntaxType = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "dsbackup.ad_backup_abstract_syntax",
	.tp_doc = "ad_backup_abstract_syntax()\n"PY_DOC_AD_BACKUP_SYNTAX,
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = syntax_ad_backup_new,
};


const struct PyNdrRpcMethodDef py_ndr_ad_restore_methods[] = {
	{ NULL }
};

static PyObject *interface_ad_restore_new(PyTypeObject *type, PyObject *args, PyObject *kwargs)
{
	return py_dcerpc_interface_init_helper(type, args, kwargs, &ndr_table_ad_restore);
}

#define PY_DOC_AD_RESTORE "Restoring Active Directory backups"
static PyTypeObject ad_restore_InterfaceType = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "dsbackup.ad_restore",
	.tp_basicsize = sizeof(dcerpc_InterfaceObject),
	.tp_doc = "ad_restore(binding, lp_ctx=None, credentials=None) -> connection\n"
"\n"
"binding should be a DCE/RPC binding string (for example: ncacn_ip_tcp:127.0.0.1)\n"
"lp_ctx should be a path to a smb.conf file or a param.LoadParm object\n"
"credentials should be a credentials.Credentials object.\n\n"PY_DOC_AD_RESTORE,
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = interface_ad_restore_new,
};

static PyObject *syntax_ad_restore_new(PyTypeObject *type, PyObject *args, PyObject *kwargs)
{
	return py_dcerpc_syntax_init_helper(type, args, kwargs, &ndr_table_ad_restore.syntax_id);
}

#define PY_DOC_AD_RESTORE_SYNTAX "Restoring Active Directory backups"
static PyTypeObject ad_restore_SyntaxType = {
	PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "dsbackup.ad_restore_abstract_syntax",
	.tp_doc = "ad_restore_abstract_syntax()\n"PY_DOC_AD_RESTORE_SYNTAX,
	.tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
	.tp_new = syntax_ad_restore_new,
};

static PyMethodDef dsbackup_methods[] = {
	{ NULL, NULL, 0, NULL }
};

static struct PyModuleDef moduledef = {
	PyModuleDef_HEAD_INIT,
	.m_name = "dsbackup",
	.m_doc = "dsbackup DCE/RPC",
	.m_size = -1,
	.m_methods = dsbackup_methods,
};
MODULE_INIT_FUNC(dsbackup)
{
	PyObject *m;
	PyObject *dep_samba_dcerpc_base;
	PyObject *dep_samba_dcerpc_misc;

	dep_samba_dcerpc_base = PyImport_ImportModule("samba.dcerpc.base");
	if (dep_samba_dcerpc_base == NULL)
		return NULL;

	dep_samba_dcerpc_misc = PyImport_ImportModule("samba.dcerpc.misc");
	if (dep_samba_dcerpc_misc == NULL)
		return NULL;

	ClientConnection_Type = (PyTypeObject *)PyObject_GetAttrString(dep_samba_dcerpc_base, "ClientConnection");
	if (ClientConnection_Type == NULL)
		return NULL;

	ndr_syntax_id_Type = (PyTypeObject *)PyObject_GetAttrString(dep_samba_dcerpc_misc, "ndr_syntax_id");
	if (ndr_syntax_id_Type == NULL)
		return NULL;

	ad_backup_InterfaceType.tp_base = ClientConnection_Type;

	ad_backup_SyntaxType.tp_base = ndr_syntax_id_Type;
	ad_backup_SyntaxType.tp_basicsize = pytalloc_BaseObject_size();

	ad_restore_InterfaceType.tp_base = ClientConnection_Type;

	ad_restore_SyntaxType.tp_base = ndr_syntax_id_Type;
	ad_restore_SyntaxType.tp_basicsize = pytalloc_BaseObject_size();

	if (PyType_Ready(&ad_backup_InterfaceType) < 0)
		return NULL;
	if (PyType_Ready(&ad_backup_SyntaxType) < 0)
		return NULL;
	if (PyType_Ready(&ad_restore_InterfaceType) < 0)
		return NULL;
	if (PyType_Ready(&ad_restore_SyntaxType) < 0)
		return NULL;
	if (!PyInterface_AddNdrRpcMethods(&ad_backup_InterfaceType, py_ndr_ad_backup_methods))
		return NULL;

	if (!PyInterface_AddNdrRpcMethods(&ad_restore_InterfaceType, py_ndr_ad_restore_methods))
		return NULL;

#ifdef PY_AD_BACKUP_PATCH
	PY_AD_BACKUP_PATCH(&ad_backup_InterfaceType);
#endif
#ifdef PY_AD_BACKUP_ABSTRACT_SYNTAX_PATCH
	PY_AD_BACKUP_ABSTRACT_SYNTAX_PATCH(&ad_backup_SyntaxType);
#endif
#ifdef PY_ABSTRACT_SYNTAX_PATCH
	PY_ABSTRACT_SYNTAX_PATCH(&ad_backup_SyntaxType);
#endif
#ifdef PY_AD_RESTORE_PATCH
	PY_AD_RESTORE_PATCH(&ad_restore_InterfaceType);
#endif
#ifdef PY_AD_RESTORE_ABSTRACT_SYNTAX_PATCH
	PY_AD_RESTORE_ABSTRACT_SYNTAX_PATCH(&ad_restore_SyntaxType);
#endif

	m = PyModule_Create(&moduledef);
	if (m == NULL)
		return NULL;

	Py_INCREF((PyObject *)(void *)&ad_backup_InterfaceType);
	PyModule_AddObject(m, "ad_backup", (PyObject *)(void *)&ad_backup_InterfaceType);
	Py_INCREF((PyObject *)(void *)&ad_backup_SyntaxType);
	PyModule_AddObject(m, "ad_backup_abstract_syntax", (PyObject *)(void *)&ad_backup_SyntaxType);
	Py_INCREF((PyObject *)(void *)&ad_backup_SyntaxType);
	PyModule_AddObject(m, "abstract_syntax", (PyObject *)(void *)&ad_backup_SyntaxType);
	Py_INCREF((PyObject *)(void *)&ad_restore_InterfaceType);
	PyModule_AddObject(m, "ad_restore", (PyObject *)(void *)&ad_restore_InterfaceType);
	Py_INCREF((PyObject *)(void *)&ad_restore_SyntaxType);
	PyModule_AddObject(m, "ad_restore_abstract_syntax", (PyObject *)(void *)&ad_restore_SyntaxType);
#ifdef PY_MOD_DSBACKUP_PATCH
	PY_MOD_DSBACKUP_PATCH(m);
#endif
	return m;

}
